Nivel 1
1.
Importa como un DataFrame el archivo sprint10.xlsx. Asegúrate de que el archivo se importa correctamente, con los nombres de columnas que le corresponden, sin manipular el archivo original.

Ordena el DataFrame por el país de origen. En caso de empate, ordena por el nombre de la ciudad.

Muestra las primeras 10 filas.

Adicionalmente, realiza un print donde compruebe que el DNI sólo tiene valores únicos.

In [3]:
import pandas as pd

# leer archivo y colocar la fila 4 como encabezado
df = pd.read_excel(r"C:\Users\gabri\Desktop\Especializacion\python\SPRINT 10\sprint10.xlsx", header=3)

# cambiar la columna unnamed por ID, ya que asi esta en el archivo original

df = df.rename(columns={"Unnamed: 0": "ID", 
                        "País d'origen": "Pais_de_origen",
                        "Dia de Naixement": "Dia_de_Naixement",
                        "Mes de Naixement": "Mes_de_Naixement",
                        "Any de Naixement": "Any_de_Naixement",
                        "Salari mensual": "Salari_mensual",
                        "No Fills": "No_Fills",
                        "Grup Professional": "Grup_Professional",
                        "Gènere" : "Genere"
                        })

# ordenar valores por país de origen y ciudad

df = df.sort_values(by=["Pais_de_origen", "Ciutat"], ascending=[True, True])

# mostrar si el Dni se repite o no

print("El Dni no se repite:", df['DNI'].is_unique)

# mostrar las primeras 10 filas del dataframe

df.head(10)

El Dni no se repite: True

,ID,Nom,Cognoms,DNI,Pais_de_origen,Ciutat,Dia_de_Naixement,Mes_de_Naixement,Any_de_Naixement,Genere,Salari_mensual,Fills,No_Fills,Grup_Professional
21,21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,1.0,Grup A
154,154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,1.0,NaN,Grup B
224,224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,1.0,Grup B
278,278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,1.0,NaN,Grup B
602,602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,1.0,NaN,Grup D
871,871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,1.0,NaN,Grup A
281,281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,1.0,Grup A
435,435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,1.0,Grup C
444,444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,1.0,NaN,Grup C
487,487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,1.0,Grup B

2.
Crea una columna que sea el nombre completo.

Crea una columna si la persona ha nacido en España o no.

Pone el DNI como índice del DataFrame (nombres de filas).

Sustituye el nombre de las columnas Día de Nacimiento, Mes de Nacimiento y Año de Nacimiento por Día, Mes y Año.

Sustituye a H por Hombre, D por Mujer, A por Otros y NC por un dato faltante (enano/null/na).

Muestra todos los cambios que has realizado en una sola tabla.

In [4]:

import numpy as np



#insertar en la posicion 3 la columna con el nombre completo, concatenando el nombre y el apellido
df.insert(3, "Nom_Complet", df["Nom"] + " " + df["Cognoms"], True)

# insertar columna que diga si ha nacido en españa o no, con el valor True o False 
df.insert(7, "Nascuda_a_Espanya", df["Pais_de_origen"] == "Espanya", True)

#hacer que el index sea iguala al DNI
df.index = df["DNI"]
df.drop(columns=["DNI"], inplace=True)

#cambiar nombre de las columnas 
df = df.rename(columns={"Dia_de_Naixement": "Dia", 
                        "Mes_de_Naixement": "Mes", 
                        "Any_de_Naixement": "Any"})

#cambiar los valores de la columna género, poniendo en lugar de A, D, H y NC, Altres, Dona, Home y NaN respectivamente
df["Genere"] = df["Genere"].replace(
    {
    "A": "Altres",
    "D": "Dona",
    "H": "Home",
    "NC": np.nan
    })

cambiados = df[["Nom_Complet", "Nascuda_a_Espanya","Dia", "Mes", "Any", "Genere"]]
cambiados

                       Nom_Complet  Nascuda_a_Espanya  Dia  Mes   Any  Genere
DNI
28973553Z    Mia Schneider Fischer              False   22   10  1976  Altres
37399141L  Laura Schneider Fischer              False    2    2  1958    Dona
37368317L  Lea Schneider Schneider              False   23   10  2005    Dona
21390098Z              Mia Fischer              False   11    8  1950    Dona
44060014R          Jonas Schneider              False   22   11  1985    Home
...                            ...                ...  ...  ...   ...     ...
89577876S       Emily Taylor Jones              False   28    3  1958    Dona
57441590Y       George Brown Jones              False   27   12  1979    Home
58204038A       Olivia Brown Brown              False   28    8  1952  Altres
28367234K         Isla Jones Brown              False   28    3  1999    Dona
82046699J            William Smith              False   19    5  1997    Home

[1000 rows x 6 columns]

3.
Junta las columnas Hijos y No Hijos en una sola columna, utilizando el método .apply() y definiendo una función que resuelva el problema. La columna nueva debe llamarse "Hijos" y tomar los valores "Sí" o "No".

In [5]:


#Uso apply para modificar la columna fills, dependiendo si tiene hijos o no, y elimino la fila no fills del df

df["Fills"] = df["Fills"].apply(lambda x: "Si" if x == 1.0 else "No")

df = df.drop(columns=["No_Fills"])



df

,ID,Nom,Cognoms,Nom_Complet,Pais_de_origen,Ciutat,Nascuda_a_Espanya,Dia,Mes,Any,Genere,Salari_mensual,Fills,Grup_Professional
DNI,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,False,22,10,1976,Altres,951 €,No,Grup A
37399141L,154,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,False,2,2,1958,Dona,1.769 €,Si,Grup B
37368317L,224,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,False,23,10,2005,Dona,2.013 €,No,Grup B
21390098Z,278,Mia,Fischer,Mia Fischer,Alemanya,Berlín,False,11,8,1950,Dona,1.557 €,Si,Grup B
44060014R,602,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,False,22,11,1985,Home,2.754 €,Si,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,False,28,3,1958,Dona,2.033 €,No,Grup B
57441590Y,728,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,False,27,12,1979,Home,1.130 €,Si,Grup A
58204038A,751,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,False,28,8,1952,Altres,1.023 €,No,Grup A
28367234K,854,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,False,28,3,1999,Dona,1.197 €,No,Grup A
82046699J,872,William,Smith,William Smith,Regne Unit,Manchester,False,19,5,1997,Home,1.405 €,Si,Grup A

4.
Crea una tabla resumen que permita ver el sueldo medio, medio, mínimo y máximo por Género.

Ordena la tabla en función del sueldo medio.

In [6]:
# lo primero es convertir la columna de salario mensual a tipo numérico, ya que actualmente es un objeto (string) y no se pueden hacer operaciones matemáticas con ella
# se deberia haber hecho al mismo momento que la nueva tabla?? 
df["Salari_mensual"] =(
    df["Salari_mensual"]
        .str.replace(" €", "", regex=False)
        .str.replace(".", "", regex=False)
        .astype(int)
    )

df

,ID,Nom,Cognoms,Nom_Complet,Pais_de_origen,Ciutat,Nascuda_a_Espanya,Dia,Mes,Any,Genere,Salari_mensual,Fills,Grup_Professional
DNI,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,False,22,10,1976,Altres,951,No,Grup A
37399141L,154,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,False,2,2,1958,Dona,1769,Si,Grup B
37368317L,224,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,False,23,10,2005,Dona,2013,No,Grup B
21390098Z,278,Mia,Fischer,Mia Fischer,Alemanya,Berlín,False,11,8,1950,Dona,1557,Si,Grup B
44060014R,602,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,False,22,11,1985,Home,2754,Si,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,False,28,3,1958,Dona,2033,No,Grup B
57441590Y,728,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,False,27,12,1979,Home,1130,Si,Grup A
58204038A,751,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,False,28,8,1952,Altres,1023,No,Grup A
28367234K,854,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,False,28,3,1999,Dona,1197,No,Grup A
82046699J,872,William,Smith,William Smith,Regne Unit,Manchester,False,19,5,1997,Home,1405,Si,Grup A

In [7]:
#nueva tabla con el group by genero y todos los calculos
nueva_tabla = (
    df.groupby("Genere", as_index=True)
      .agg(
          Cantidad=("Genere", "count"),
          Salari_Mitja =("Salari_mensual", "mean"),
          Salari_Mediana=("Salari_mensual", "median"),
          Salari_Maxim=("Salari_mensual", "max"),
          Salari_Minim=("Salari_mensual", "min")
        ).round(2)
).sort_values(by="Salari_Mitja", ascending=False)

nueva_tabla

        Cantidad  Salari_Mitja  Salari_Mediana  Salari_Maxim  Salari_Minim
Genere
Home         449       1643.25          1531.0          3356           737
Altres        51       1626.59          1545.0          3175           703
Dona         440       1469.44          1361.5          3021           665

5.
Crea una tabla resumen con el salario medio por género (filas) y país de origen (columnas).

Añade las medias a los márgenes de la tabla.

(EXTRA): Aplica formato condicional en la tabla para ver en un color más intenso los valores más elevados

In [8]:
import pandas as pd


# Crear tabla resumen (pivot)

tabla_resumen = pd.pivot_table(
    df,
    values="Salari_mensual",
    index="Genere" ,
    columns="Pais_de_origen",
    aggfunc="mean",
    margins=True,
    margins_name="Media_Total"
)

# Redondear a 2 decimales

tabla_resumen = tabla_resumen.round(2)


# Mostrar con formato moneda + color


tabla_resumen = (
    tabla_resumen
        .style
        .format("{:,.2f} €")
        .background_gradient(cmap="YlGnBu")
)

tabla_resumen

6.
Crea una nueva columna que sea la fecha de nacimiento en formato Datetime a partir de las columnas día, mes y año. Utilizando esta columna crea una función que dada una fecha, te calcule la edad actual a día de hoy.

Utiliza la función que acabas de crear para generar una columna nueva en DataFrame con la edad actual.

In [9]:
import pandas as pd
from datetime import datetime

# funcion para crear columna con fecha de nacimiento por cada fila
def crear_fecha(fila):
    try:
        return datetime(int(fila["Any"]), int(fila["Mes"]), int(fila["Dia"]))
    except:
        return pd.NaT
# creo la columna con la fecha de nacimiento utilizando la funcion creada anteriormente
df["Data_Naixement"] = df.apply(crear_fecha, axis=1)

# funcion para calcular la edad a partir de la fecha de nacimiento
def calcular_edad(fecha_nacimiento):
    
    if pd.isna(fecha_nacimiento):
        return None
    
    hoy = datetime.now()
    edad = hoy.year - fecha_nacimiento.year
    
    # Ajuste si aún no ha cumplido años este año, si el mes y el día de hoy son menores que el mes y el día de nacimiento
    if (hoy.month, hoy.day) < (fecha_nacimiento.month, fecha_nacimiento.day):
        edad -= 1
    
    return edad
# creo la columna con la edad actual utilizando la funcion creada anteriormente
df["Edat_actual"] = df["Data_Naixement"].apply(calcular_edad)


df

,ID,Nom,Cognoms,Nom_Complet,Pais_de_origen,Ciutat,Nascuda_a_Espanya,Dia,Mes,Any,Genere,Salari_mensual,Fills,Grup_Professional,Data_Naixement,Edat_actual
DNI,,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,False,22,10,1976,Altres,951,No,Grup A,1976-10-22,49
37399141L,154,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,False,2,2,1958,Dona,1769,Si,Grup B,1958-02-02,68
37368317L,224,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,False,23,10,2005,Dona,2013,No,Grup B,2005-10-23,20
21390098Z,278,Mia,Fischer,Mia Fischer,Alemanya,Berlín,False,11,8,1950,Dona,1557,Si,Grup B,1950-08-11,75
44060014R,602,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,False,22,11,1985,Home,2754,Si,Grup D,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,False,28,3,1958,Dona,2033,No,Grup B,1958-03-28,67
57441590Y,728,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,False,27,12,1979,Home,1130,Si,Grup A,1979-12-27,46
58204038A,751,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,False,28,8,1952,Altres,1023,No,Grup A,1952-08-28,73
28367234K,854,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,False,28,3,1999,Dona,1197,No,Grup A,1999-03-28,26
82046699J,872,William,Smith,William Smith,Regne Unit,Manchester,False,19,5,1997,Home,1405,Si,Grup A,1997-05-19,28

Nivel 2
1.
Utilizando el siguiente DataFrame, adjunta la columna "Incremento" al dataframe del nivel anterior.

Actualiza la columna salario en función de los porcentajes que se adjuntan. No modifiques manualmente los incrementos, escribe código Python para realizar las conversiones necesarias.

df_increment = pd.DataFrame({"Grupo":["Grupo A","Grupo B","Grupo C", "Grupo D" ] , "Incremento":

["5%","3,5%","2%","8%"]})

In [10]:
#crei el dataframe con los porcentajes de incremento para cada grupo profesional
df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})

df_increment

     Grup Increment
0  Grup A        5%
1  Grup B      3,5%
2  Grup C        2%
3  Grup D        8%

In [12]:
# hago .map que es como un for, donde por cada valor de Grup Professional, busca el valor corresponiente y le asigna el valor de incremento a la nueva columna Incremento
df["Incremento"] = df["Grup_Professional"].map(
    df_increment.set_index("Grup")["Increment"] #para eso lo paso a serie panda , es como un diccionario. clave valor. Grup como clave index e increment como unica columna valor
)

df["Salari_mensual"] = (
    df["Salari_mensual"] * (                                    #lo multiplico por 1 + procentaje en decimales, para eso primero limpio y convierto a float la columna de incremento
                            1 +
                                 df["Incremento"]
                                    .str.replace("%", "", regex=False)
                                    .str.replace(",", ".", regex=False)
                                    .astype(float)
                                    / 100
                            )
                        ).round(2)

df

,ID,Nom,Cognoms,Nom_Complet,Pais_de_origen,Ciutat,Nascuda_a_Espanya,Dia,Mes,Any,Genere,Salari_mensual,Fills,Grup_Professional,Data_Naixement,Edat_actual,Incremento
DNI,,,,,,,,,,,,,,,,,
28973553Z,21,Mia,Schneider Fischer,Mia Schneider Fischer,Alemanya,Berlín,False,22,10,1976,Altres,998.55,No,Grup A,1976-10-22,49,5%
37399141L,154,Laura,Schneider Fischer,Laura Schneider Fischer,Alemanya,Berlín,False,2,2,1958,Dona,1830.92,Si,Grup B,1958-02-02,68,"3,5%"
37368317L,224,Lea,Schneider Schneider,Lea Schneider Schneider,Alemanya,Berlín,False,23,10,2005,Dona,2083.46,No,Grup B,2005-10-23,20,"3,5%"
21390098Z,278,Mia,Fischer,Mia Fischer,Alemanya,Berlín,False,11,8,1950,Dona,1611.50,Si,Grup B,1950-08-11,75,"3,5%"
44060014R,602,Jonas,Schneider,Jonas Schneider,Alemanya,Berlín,False,22,11,1985,Home,2974.32,Si,Grup D,1985-11-22,40,8%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,547,Emily,Taylor Jones,Emily Taylor Jones,Regne Unit,Manchester,False,28,3,1958,Dona,2104.15,No,Grup B,1958-03-28,67,"3,5%"
57441590Y,728,George,Brown Jones,George Brown Jones,Regne Unit,Manchester,False,27,12,1979,Home,1186.50,Si,Grup A,1979-12-27,46,5%
58204038A,751,Olivia,Brown Brown,Olivia Brown Brown,Regne Unit,Manchester,False,28,8,1952,Altres,1074.15,No,Grup A,1952-08-28,73,5%
28367234K,854,Isla,Jones Brown,Isla Jones Brown,Regne Unit,Manchester,False,28,3,1999,Dona,1256.85,No,Grup A,1999-03-28,26,5%
82046699J,872,William,Smith,William Smith,Regne Unit,Manchester,False,19,5,1997,Home,1475.25,Si,Grup A,1997-05-19,28,5%

2.
Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...

Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [15]:
# crear bucle, por cada grup, crear un archivo dades_grup.xlsx con las filas correspondientes a ese grup
for grup, dades in df.groupby("Grup_Professional"):
    
    # Limpiar nombre para archivo (sin espacios)
    nom_fitxer = f"dades_{grup.replace(' ', '')}.xlsx"
    
    dades.to_excel(nom_fitxer)

df_resum = (
    df
    .groupby("Grup_Professional")
    .agg(
        treballadors=("Grup_Professional", "count"),
        salari_mig=("Salari_mensual", "mean"),
        edat_mediana=("Edat_actual", "median")
    )
    .reset_index()
)
df_resum["salari_mig"] = df_resum["salari_mig"].round(2)
df_resum.to_excel("resum_grups.xlsx", index=False)

Nivell 3
El nivell 3 d’aquest sprint és totalment diferent a d’altres sprints que has fet fins ara, ja que són exercicis més abstractes que requereixen barallar-s’hi bastant. No continuen amb el mateix dataset dels nivells anteriors, sinó que et plantegen dues situacions noves totalment diferents entre elles.

1.
Crea una funció que prengui un dataframe com a paràmetre d'entrada.

La funció ha de crear (i exportar) un gràfic automàticament per a cada columna del dataframe. Per exemple:

un histograma/boxplot si la variable és numèrica
unes barres dels valors més freqüents si és categòrica
unes barres dels anys més freqüents si la dada està en format data.
La idea és crear una funció que funcioni per qualsevol dataframe, no només amb el que hem treballat fins ara.

Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

Tingues en consideració que en el següent sprint treballaràs exclusivament amb gràfics. L’objectiu d’aquest exercici no és crear gràfics molt elaborats, sinó resoldre una necessitat de manera ràpida i automàtica.

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

def generar_graficos_automaticos(df, carpeta_salida="graficos"):
    
    os.makedirs(carpeta_salida, exist_ok=True)
    
    for columna in df.columns:
        
        serie = df[columna].dropna()
        
        # Saltar columnas vacías
        if serie.empty:
            continue
        
        plt.figure(figsize=(6,4))
        
        # Numéricas  (excluyendo booleanos)
        if (
            pd.api.types.is_numeric_dtype(serie) and
            not pd.api.types.is_bool_dtype(serie)
        ):
            serie.plot(kind="hist", bins=20)
            plt.title(f"Histograma de {columna}")
        
        # Fechas
        elif pd.api.types.is_datetime64_any_dtype(serie):
            años = serie.dt.year.value_counts().sort_index()
            años.plot(kind="bar")
            plt.title(f"Años más frecuentes - {columna}")
        
        # Categóricas o booleanas
        else:
            serie.value_counts().head(10).plot(kind="bar")
            plt.title(f"Top 10 valores - {columna}")
        
        ruta = os.path.join(carpeta_salida, f"{columna}.png")
        plt.tight_layout()
        plt.savefig(ruta)
        plt.close()
generar_graficos_automaticos(df)

df_iris = sns.load_dataset("iris")
df_titanic = sns.load_dataset("titanic")

generar_graficos_automaticos(df_iris, carpeta_salida="graficos_iris")
generar_graficos_automaticos(df_titanic, carpeta_salida="graficos_titanic")

2.
Carrega l'arxiu matriu_distancies.xlsx a pandas, de manera que els noms de files i els noms de columnes siguin els de les ciutats. Borra "Las Palmas de Gran Canaria" i "Palma" perquè poguem fer el trajecte en cotxe.

Font: Mejores Rutas

Ens interessa visitar totes les ciutats principals d'Espanya recorrent la mínima distància possible.

No cal que ho facis de forma òptima, ens interessa que desenvolupis una solució raonable utilitzant les eines que tens actualment.

Per exemple, una aproximació senzilla (que no òptima) seria anant sempre a la ciutat més propera que no haguem visitat encara

Fes una funció que donada la matriu de distàncies i la ciutat d'origen, faci una proposta de ruta que sigui el més curta possible que puguis, retornant una llista amb l'ordre de visita. Dóna també la distància total recorreguda.

(EXTRA) Des de quina ciutat la ruta seria més curta amb l'algoritme plantejat

In [ ]:
import pandas as pd
# cargo el archivo de excel coloncado la primer columna como indice
df_dist = pd.read_excel(
    "matriu_distancies.xlsx",
    index_col=0
)
# borro las ciudades que no se puede acceder en coche directamente.
df_dist = df_dist.drop(
    index=["Las Palmas de Gran Canaria", "Palma"],
    columns=["Las Palmas de Gran Canaria", "Palma"]
)
#Creo la funcion para calcular la ruta, tomando la matriz y la ciudad dada 
def ruta_simple(matriz, ciudad_origen): 
    
    ciudades_no_visitadas = list(matriz.index)
    ciudades_no_visitadas.remove(ciudad_origen)  #creo la variable de ciudades no visitadas eliminando la ciudad de origen para que no haya repetidos.

# creo los valores iniciales de la ruta, la distancia total y la ciudad actual 
    ruta = [ciudad_origen]
    distancia_total = 0
    ciudad_actual = ciudad_origen
    
    while ciudades_no_visitadas:        #utilizo while ciudades_no_visitadas, para que se repita hasta que no haya mas ciudades no visitadas.
        
        # Buscar ciudad más cercana no visitada
        distancias = matriz.loc[ciudad_actual, ciudades_no_visitadas]
        siguiente_ciudad = distancias.idxmin()                          #siguiente ciudad = nombre de la ciudad con la distancia minima 
        
        distancia_total += distancias.min()                             # sumo el valor minimo a la distancia total 
        
        ruta.append(siguiente_ciudad)                                   #agrego siguiente ciudad a la ruta y la elimino de las ciudades no visitadas para que no se repita
        ciudades_no_visitadas.remove(siguiente_ciudad)
        
        ciudad_actual = siguiente_ciudad                                #ahora la ciudad actual es la siguiente ciudad y repite el proceso.
    
    return ruta, distancia_total

ruta, distancia = ruta_simple(df_dist, "Barcelona")

print("Ruta propuesta:")
print(ruta)

print("Distancia total:")
print(distancia)

Ruta propuesta:
['Barcelona', 'Hospitalet de Llobregat', 'Zaragoza', 'Valencia', 'Alicante', 'Murcia', 'Córdoba', 'Sevilla', 'Málaga', 'Valladolid', 'Gijón', 'Bilbao', 'Vigo']
Distancia total:
2778.0

In [ ]:
def mejor_origen(matriz):
    
    mejor_distancia = float("inf")
    mejor_ciudad = None
    mejor_ruta = None
    
    for ciudad in matriz.index:       #por cada ciudad en el indice de la matriz, ejecutar la funcion ruta_simple y encontrar la ciudad de origen con la ruta mas corta.
        
        ruta, distancia = ruta_simple(matriz, ciudad)
        
        if distancia < mejor_distancia:
            mejor_distancia = distancia
            mejor_ciudad = ciudad
            mejor_ruta = ruta
    
    return mejor_ciudad, mejor_distancia, mejor_ruta  #devolver la mejor ciudad, la mejor distancia y la mejor ruta

ciudad, distancia, ruta = mejor_origen(df_dist)

print("Mejor ciudad de inicio:", ciudad)
print("Distancia:", distancia)
print("Ruta:", ruta)

Mejor ciudad de inicio: Barcelona
Distancia: 2778.0
Ruta: ['Barcelona', 'Hospitalet de Llobregat', 'Zaragoza', 'Valencia', 'Alicante', 'Murcia', 'Córdoba', 'Sevilla', 'Málaga', 'Valladolid', 'Gijón', 'Bilbao', 'Vigo']